jarsigner -keystore myKeys -storepass 123456 PunchScan-auditor-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 PunchScan-authoring-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 PunchScan-common-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 PunchScan-engine-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 PunchScan-pollingPlace-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 PunchScan-upload-1.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\ballotStandard-1.0.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\itext-1.4.5.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\swing-layout-1.0.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\dom.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\jaxp-api.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\xalan.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\xercesImpl.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\xmldsig.jar jdc
jarsigner -keystore myKeys -storepass 123456 extJars\xmlSig\xmlsec.jar jdc
